// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StimulationAppAPI.DAL.Context;

#nullable disable

namespace StimulationAppAPI.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20230412192637_FixRelationship")]
    partial class FixRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StimulationAppAPI.DAL.Model.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("UserName");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserName = "Nicolas",
                            Email = "nic.vanruy@gmail.com",
                            FirstName = "Nicolas",
                            LastName = "Vanruysseveldt",
                            Role = "Admin"
                        },
                        new
                        {
                            UserName = "Joske",
                            Email = "Joske.Peeters@gmail.com",
                            FirstName = "Joske",
                            LastName = "Peeters",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("StimulationAppAPI.DAL.Model.UserLogin", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserName");

                    b.ToTable("Login");

                    b.HasData(
                        new
                        {
                            UserName = "Nicolas",
                            Password = "Test123"
                        },
                        new
                        {
                            UserName = "Joske",
                            Password = "Test123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
